services:
  - type: web
    name: pdf-qa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false  # You set this manually in the Render dashboard
