services:
  - type: web
    name: SimpleAiproject
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free                  
    region: oregon              
