services:
  - type: web
    name: pdf-qa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: GROQ_API_KEY
        sync: false  # You set this manually in the Render dashboard
